vich_uploader:
    db_driver: orm

    mappings:
        car:
            uri_prefix: /images/cars
            upload_destination: '%kernel.project_dir%/public/images/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
